package frames;

public class Cajas extends javax.swing.JInternalFrame {

    AperturaYGestionCaja agc = new AperturaYGestionCaja();
    CerrarCaja cc = new CerrarCaja(this);

    public Cajas() {
        initComponents();
        paneCaja.addTab("Movimientos caja", agc);
        paneCaja.addTab("Cerrar caja", cc);
        paneCaja.setSelectedComponent(agc);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        paneCaja = new javax.swing.JTabbedPane();

        setClosable(true);
        setTitle("CAJA");

        paneCaja.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                paneCajaStateChanged(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(paneCaja, javax.swing.GroupLayout.DEFAULT_SIZE, 1049, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(paneCaja, javax.swing.GroupLayout.DEFAULT_SIZE, 614, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void paneCajaStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_paneCajaStateChanged
        if (Principal.caja.isEstado() == false) {
            cc.limpiar();
        } else {
            cc.setDatos();
        }
    }//GEN-LAST:event_paneCajaStateChanged


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTabbedPane paneCaja;
    // End of variables declaration//GEN-END:variables
}
