/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package etapa3.guia2.ejextra1;

import Entidades.Tareas;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Usuario
 */
public class MenuTareas extends javax.swing.JFrame {
    
    DefaultTableModel modelo = new DefaultTableModel();

    /**
     * Creates new form MenuTareas
     */
    public MenuTareas() {
        initComponents();
        armarCabecera();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jtEscribirTarea = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jtTareas = new javax.swing.JTable();
        jbAgregarTarea = new javax.swing.JButton();
        jtTareaCompletada = new javax.swing.JToggleButton();
        jbEliminarTarea = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(600, 600));

        jLabel1.setFont(new java.awt.Font("Arial Black", 1, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 102, 51));
        jLabel1.setText("Tareas");

        jLabel2.setFont(new java.awt.Font("Arial Narrow", 2, 18)); // NOI18N
        jLabel2.setText("Ingrese la tarea");

        jtTareas.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jtTareas);

        jbAgregarTarea.setFont(new java.awt.Font("Arial Narrow", 1, 24)); // NOI18N
        jbAgregarTarea.setText("Agregar");
        jbAgregarTarea.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbAgregarTareaActionPerformed(evt);
            }
        });

        jtTareaCompletada.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconos/Tilde.png"))); // NOI18N
        jtTareaCompletada.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconos/Tilde.png"))); // NOI18N
        jtTareaCompletada.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconos/Tilde.png"))); // NOI18N
        jtTareaCompletada.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtTareaCompletadaActionPerformed(evt);
            }
        });

        jbEliminarTarea.setFont(new java.awt.Font("Arial Narrow", 1, 24)); // NOI18N
        jbEliminarTarea.setText("Eliminar");
        jbEliminarTarea.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbEliminarTareaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane1)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addGap(18, 18, 18)
                                .addComponent(jtEscribirTarea))))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap(67, Short.MAX_VALUE)
                        .addComponent(jbAgregarTarea, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(61, 61, 61)
                        .addComponent(jtTareaCompletada, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(64, 64, 64)
                        .addComponent(jbEliminarTarea, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(58, 58, 58)))
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(225, 225, 225))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(jtEscribirTarea, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(69, 69, 69)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jbEliminarTarea, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jtTareaCompletada, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)))
                    .addComponent(jbAgregarTarea, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 63, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 331, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jbAgregarTareaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbAgregarTareaActionPerformed
        try {
            if (jtEscribirTarea.getText().isEmpty()) {
                JOptionPane.showMessageDialog(this, "Debe ingresar una tarea");
                return;
            }
            
            Tareas tareas = new Tareas(jtEscribirTarea.getText(), false);
            cargarDatos(tareas);
            JOptionPane.showMessageDialog(this, "La tarea ha sido agregada exitosamente");
            jtEscribirTarea.setText("");
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Ha ocurrido un error");
            jtEscribirTarea.setText("");
        }
        
    }//GEN-LAST:event_jbAgregarTareaActionPerformed

    private void jbEliminarTareaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbEliminarTareaActionPerformed
        try {
            int filaSeleccionada = jtTareas.getSelectedRow();
            if (filaSeleccionada != -1) {
                modelo.removeRow(filaSeleccionada);
                JOptionPane.showMessageDialog(this, "La tarea ha sido borrada exitosamente");
            } else {
                JOptionPane.showMessageDialog(this, "Debe seleccionar un elemento de la lista");
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Ha ocurrido un error");
            jtEscribirTarea.setText("");
        }
    }//GEN-LAST:event_jbEliminarTareaActionPerformed

    private void jtTareaCompletadaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtTareaCompletadaActionPerformed
        int filaSeleccionada = jtTareas.getSelectedRow();
        Tareas newTarea = new Tareas(jtTareas.getName(), true);
        if (filaSeleccionada != -1) {
            modelo.setValueAt(CompletadaNoCompletada(newTarea), filaSeleccionada, 1);
        }
    }//GEN-LAST:event_jtTareaCompletadaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MenuTareas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MenuTareas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MenuTareas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MenuTareas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MenuTareas().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton jbAgregarTarea;
    private javax.swing.JButton jbEliminarTarea;
    private javax.swing.JTextField jtEscribirTarea;
    private javax.swing.JToggleButton jtTareaCompletada;
    private javax.swing.JTable jtTareas;
    // End of variables declaration//GEN-END:variables

    private void armarCabecera() {
        
        modelo.addColumn("TAREA");
        modelo.addColumn("ESTADO");
        jtTareas.setModel(modelo);
    }
    
    private void cargarDatos(Tareas tareas) {
        modelo.addRow(new Object[]{tareas.getNombre(), CompletadaNoCompletada(tareas)});
    }
    
    private String CompletadaNoCompletada(Tareas tareas) {
        if (tareas.isEstado() == false) {
            return "NO COMPLETADA";
        } else {
            return "COMPLETADA";
        }
    }
}
