/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package InternalFrames;

import etapa3.guia2.ej4.MenuPrincipal;
import Entidades.Producto;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Usuario
 */
public class BusquedaPorPrecio extends javax.swing.JInternalFrame {

    DefaultTableModel modelo2 = new DefaultTableModel();

    public boolean isCellEditable2(int c, int f) {
        return false;
    }

    public BusquedaPorPrecio() {
        initComponents();
        armarCabeceraTabla();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jtProductos2 = new javax.swing.JTable();
        jLabel3 = new javax.swing.JLabel();
        jtMenor = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jtMayor = new javax.swing.JTextField();

        setClosable(true);
        setPreferredSize(new java.awt.Dimension(400, 300));

        jLabel1.setFont(new java.awt.Font("Arial Narrow", 3, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 102, 255));
        jLabel1.setText("Listado por \"Precio ($)\"");

        jtProductos2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jtProductos2);

        jLabel3.setText("Entre $:");

        jtMenor.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jtMenorKeyReleased(evt);
            }
        });

        jLabel2.setText("y");

        jtMayor.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jtMayorKeyReleased(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(63, Short.MAX_VALUE)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 234, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(87, 87, 87))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(66, 66, 66)
                .addComponent(jLabel3)
                .addGap(18, 18, 18)
                .addComponent(jtMenor, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jtMayor, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(14, 14, 14)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jtMenor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2)
                    .addComponent(jtMayor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 172, Short.MAX_VALUE)
                .addGap(6, 6, 6))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jtMenorKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtMenorKeyReleased
        borrarFilas();
        try {
            for (Producto prod : MenuPrincipal.listaProductos) {
                Double precioMenor = Double.parseDouble(jtMenor.getText());
                if (prod.getPrecio() >= precioMenor) {
                    modelo2.addRow(new Object[]{
                        prod.getCodigo(),
                        prod.getDescripción(),
                        prod.getPrecio(),
                        prod.getStock()
                    });
                }

            }
        } catch (NumberFormatException nf) {
            JOptionPane.showMessageDialog(this, "Debe ingresar un monto");
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Debe ingresar un monto");
        }
    }//GEN-LAST:event_jtMenorKeyReleased

    private void jtMayorKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtMayorKeyReleased
        borrarFilas();
        try {
            for (Producto prod : MenuPrincipal.listaProductos) {
                Double precioMayor = Double.parseDouble(jtMayor.getText());
                if (prod.getPrecio() <= precioMayor) {
                    modelo2.addRow(new Object[]{
                        prod.getCodigo(),
                        prod.getDescripción(),
                        prod.getPrecio(),
                        prod.getStock()
                    });
                }

            }
        } catch (NumberFormatException nf) {
            JOptionPane.showMessageDialog(this, "Debe ingresar un monto");
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Debe ingresar un monto");
        }
    }//GEN-LAST:event_jtMayorKeyReleased


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField jtMayor;
    private javax.swing.JTextField jtMenor;
    private javax.swing.JTable jtProductos2;
    // End of variables declaration//GEN-END:variables

    private void armarCabeceraTabla() {
        modelo2.addColumn("Codigo");
        modelo2.addColumn("Descripcion");
        modelo2.addColumn("Precio ($)");
        modelo2.addColumn("Stock");
        jtProductos2.setModel(modelo2);
    }

//IR BORRANDO FILAS QUE NO PERTENECEN A LA BUSQUEDA//
    private void borrarFilas() {
        int f = jtProductos2.getRowCount() - 1;
        for (; f >= 0; f--) {
            modelo2.removeRow(f);
        }

    }

}
