/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package InternalFrames;

import Entidades.Producto;
import Entidades.Categorias;
import etapa3.guia2.ej4.MenuPrincipal;
import java.awt.Image;
import java.util.Iterator;
import javax.swing.Icon;
import javax.swing.ImageIcon;
import javax.swing.JLabel;
import javax.swing.JOptionPane;

/**
 *
 * @author Usuario
 */
public class GestionDeProductos extends javax.swing.JInternalFrame {

    /**
     * Creates new form GestionDeProductos
     */
    public GestionDeProductos() {
        initComponents();
        cargarCombo();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jtCodigo = new javax.swing.JTextField();
        jbBusqueda = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jtDescripcion = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jtPrecio = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jcCategorias = new javax.swing.JComboBox<>();
        jLabel6 = new javax.swing.JLabel();
        jtStock = new javax.swing.JTextField();
        jbNuevoProducto = new javax.swing.JButton();
        jbModificarProducto = new javax.swing.JButton();
        jbEliminarProducto = new javax.swing.JButton();
        jbSalir = new javax.swing.JButton();

        setPreferredSize(new java.awt.Dimension(400, 500));

        jLabel1.setFont(new java.awt.Font("Arial Narrow", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(51, 102, 255));
        jLabel1.setText("Gestion de Productos");

        jLabel2.setFont(new java.awt.Font("Arial Narrow", 0, 14)); // NOI18N
        jLabel2.setText("Código:");

        jbBusqueda.setIcon(new javax.swing.ImageIcon(getClass().getResource("/etapa3/guia2/ej4/botones/LupaReducida.png"))); // NOI18N
        jbBusqueda.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/etapa3/guia2/ej4/botones/LupaReducida.png"))); // NOI18N
        jbBusqueda.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/etapa3/guia2/ej4/botones/LupaReducida.png"))); // NOI18N
        jbBusqueda.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbBusquedaActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Arial Narrow", 0, 14)); // NOI18N
        jLabel3.setText("Descripción:");

        jLabel4.setFont(new java.awt.Font("Arial Narrow", 0, 14)); // NOI18N
        jLabel4.setText("Precio ($):");

        jLabel5.setFont(new java.awt.Font("Arial Narrow", 0, 14)); // NOI18N
        jLabel5.setText("Rubro:");

        jcCategorias.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jcCategoriasActionPerformed(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Arial Narrow", 0, 14)); // NOI18N
        jLabel6.setText("Stock:");

        jbNuevoProducto.setFont(new java.awt.Font("Arial Narrow", 0, 14)); // NOI18N
        jbNuevoProducto.setText("Nuevo");
        jbNuevoProducto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbNuevoProductoActionPerformed(evt);
            }
        });

        jbModificarProducto.setFont(new java.awt.Font("Arial Narrow", 0, 14)); // NOI18N
        jbModificarProducto.setText("Guardar");
        jbModificarProducto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbModificarProductoActionPerformed(evt);
            }
        });

        jbEliminarProducto.setFont(new java.awt.Font("Arial Narrow", 0, 14)); // NOI18N
        jbEliminarProducto.setText("Eliminar");
        jbEliminarProducto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbEliminarProductoActionPerformed(evt);
            }
        });

        jbSalir.setFont(new java.awt.Font("Arial Narrow", 1, 14)); // NOI18N
        jbSalir.setText("SALIR");
        jbSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbSalirActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(16, 16, 16)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel6)
                            .addComponent(jLabel5)
                            .addComponent(jLabel4)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(jtCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(18, 18, 18)
                                    .addComponent(jbBusqueda, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addComponent(jtDescripcion)
                                .addComponent(jtPrecio, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jcCategorias, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addComponent(jtStock, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jbNuevoProducto)
                        .addGap(18, 18, 18)
                        .addComponent(jbModificarProducto)
                        .addGap(18, 18, 18)
                        .addComponent(jbEliminarProducto)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 50, Short.MAX_VALUE)
                        .addComponent(jbSalir)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(35, 35, 35)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(jtCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(26, 26, 26)
                        .addComponent(jbBusqueda, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jtDescripcion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(29, 29, 29)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jtPrecio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(34, 34, 34)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(jcCategorias, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(38, 38, 38)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(jtStock, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 78, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jbNuevoProducto)
                    .addComponent(jbModificarProducto)
                    .addComponent(jbEliminarProducto)
                    .addComponent(jbSalir))
                .addGap(49, 49, 49))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jcCategoriasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jcCategoriasActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jcCategoriasActionPerformed

    private void jbNuevoProductoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbNuevoProductoActionPerformed
        try {
            int cod = Integer.parseInt(jtCodigo.getText());
            String desc = jtDescripcion.getText();
            Double precio = Double.parseDouble(jtPrecio.getText());
            Categorias cat = (Categorias) jcCategorias.getSelectedItem();
            int stock = Integer.parseInt(jtStock.getText());
            Producto prod = new Producto(cod, desc, precio, stock, cat);
            MenuPrincipal.listaProductos.add(prod);
            JOptionPane.showMessageDialog(this, "El Producto fue registrado exitosamente");
            jtCodigo.setText("");
            jtDescripcion.setText("");
            jtPrecio.setText("");
            jtStock.setText("");
        } catch (NumberFormatException nf) {
            JOptionPane.showMessageDialog(this, "Debe llenar todos los campos");
            jtCodigo.setText("");
            jtDescripcion.setText("");
            jtPrecio.setText("");
            jtStock.setText("");
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Ha ocurrido un error");
            jtCodigo.setText("");
            jtDescripcion.setText("");
            jtPrecio.setText("");
            jtStock.setText("");
        }
    }//GEN-LAST:event_jbNuevoProductoActionPerformed

    private void jbBusquedaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbBusquedaActionPerformed
        try {
            for (Producto prod : MenuPrincipal.listaProductos) {
                if (prod.getCodigo() == (Integer.parseInt(jtCodigo.getText()))) {
                    jtDescripcion.setText(prod.getDescripción());
                    jtPrecio.setText(prod.getPrecio() + "");
                    jtStock.setText(prod.getStock() + "");
                    jcCategorias.setSelectedItem(prod.getRubros());
                }
            }
        } catch (NumberFormatException nf) {
            JOptionPane.showMessageDialog(this, "Debe ingresar el código de Producto");
            jtCodigo.setText("");
            jtDescripcion.setText("");
            jtPrecio.setText("");
            jtStock.setText("");
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Ha ocurrido un error");
            jtCodigo.setText("");
            jtDescripcion.setText("");
            jtPrecio.setText("");
            jtStock.setText("");
        }

    }//GEN-LAST:event_jbBusquedaActionPerformed

    private void jbModificarProductoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbModificarProductoActionPerformed

        try {
            Integer newCodigo = Integer.parseInt(jtCodigo.getText());
            String newDescripcion = jtDescripcion.getText();
            Double newPrecio = Double.parseDouble(jtPrecio.getText());
            Integer newStock = Integer.parseInt(jtStock.getText());
            Categorias newCategoria = (Categorias) jcCategorias.getSelectedItem();
            int respuesta = JOptionPane.showConfirmDialog(this, "¿Realmente desea realizar los cambios?", "ALERTA!!!", JOptionPane.YES_NO_OPTION);
            if (respuesta == JOptionPane.YES_OPTION) {
                for (Producto prod : MenuPrincipal.listaProductos) {
                    if (prod.getCodigo()==newCodigo) {
                        MenuPrincipal.listaProductos.remove(prod);
                        prod.setCodigo(newCodigo);
                        prod.setDescripción(newDescripcion);
                        prod.setPrecio(newPrecio);
                        prod.setRubros(newCategoria);
                        prod.setStock(newStock);
                        MenuPrincipal.listaProductos.add(prod);
                        break;
                    } else if (respuesta == JOptionPane.NO_OPTION) {
                        break;
                    }

                }
            }
        } catch (NumberFormatException nf) {
            JOptionPane.showMessageDialog(this, "Debe ingresar el código del Producto");
            jtCodigo.setText("");
            jtDescripcion.setText("");
            jtPrecio.setText("");
            jtStock.setText("");
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Ha ocurrido un error");
            jtCodigo.setText("");
            jtDescripcion.setText("");
            jtPrecio.setText("");
            jtStock.setText("");
        }

    }//GEN-LAST:event_jbModificarProductoActionPerformed

    private void jbSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbSalirActionPerformed
        MenuPrincipal.Escritorio.removeAll();
        MenuPrincipal.Escritorio.repaint();
    }//GEN-LAST:event_jbSalirActionPerformed

    private void jbEliminarProductoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbEliminarProductoActionPerformed
        Iterator<Producto> it = MenuPrincipal.listaProductos.iterator();

        try {
            int codigo = Integer.parseInt(jtCodigo.getText());
            while (it.hasNext()) {
                if (it.next().getCodigo() == codigo) {
                    it.remove();
                }
            }
            JOptionPane.showMessageDialog(this, "El Producto se ha eliminado exitosamente");
            jtCodigo.setText("");
            jtDescripcion.setText("");
            jtPrecio.setText("");
            jtStock.setText("");
        } catch (NumberFormatException nf) {
            JOptionPane.showMessageDialog(this, "Debe ingresar el código de Producto");
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Ha ocurrido un error");
            jtCodigo.setText("");
            jtDescripcion.setText("");
            jtPrecio.setText("");
            jtStock.setText("");
        }

    }//GEN-LAST:event_jbEliminarProductoActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JButton jbBusqueda;
    private javax.swing.JButton jbEliminarProducto;
    private javax.swing.JButton jbModificarProducto;
    private javax.swing.JButton jbNuevoProducto;
    private javax.swing.JButton jbSalir;
    private javax.swing.JComboBox<Categorias> jcCategorias;
    private javax.swing.JTextField jtCodigo;
    private javax.swing.JTextField jtDescripcion;
    private javax.swing.JTextField jtPrecio;
    private javax.swing.JTextField jtStock;
    // End of variables declaration//GEN-END:variables

    private void cargarCombo() {
        jcCategorias.addItem(Categorias.LIMPIEZA);
        jcCategorias.addItem(Categorias.COMESTIBLES);
        jcCategorias.addItem(Categorias.PERFUMERIA);
    }
}
